openapi: 3.0.1
info:
  title: ''
  description: ''
  version: "1.0"

paths:
  /upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MultipartData'
      responses:
        200:
          description: ''
          content:
            application/json: {}
components:
  schemas:
    MultipartData:
      type: object
      properties:
        file:
          format: binary
          type: string
        name:
          pattern: .*
          type: string
